### ISSUE TITLE
SCSS fail to compile

### ISSUE THREAD

**Issue by sixclones** [gweltaz-calori/webpack-boilerplate#4]
Compiled
```scss
.nav {
	width: 100%;
	margin-top: 15px;
	text-align: center
	&-link {
		color: $white;
	}
	&:nth-child(1) {
		margin-right: 15px;
	}
}
```

Fail to compile
```scss
.nav {
	width: 100%;
	margin-top: 15px;
	text-align: center
	&-link {
		color: $white;
        	&:nth-child(1) {
		         margin-right: 15px;
	        }
	}
}
```
